services:
  api:
    restart: always
    build: .
    ports:
      - "7001:8080"
    volumes:
      - .:/api
    environment:
      DEBUG: "true"
    command: uv run fastapi dev example/main.py --host 0.0.0.0 --port 8080

  redis:
    image: redis:7.0.0-alpine
    ports:
      - "6388:6379"
    command: redis-server
