services:
  api:
    restart: always
    build: .
    ports:
      - "7001:8080"
    volumes:
      - .:/api
    environment:
      DEBUG: "true"
    command: uv run fastapi dev example/main.py --host 0.0.0.0 --port 8080

  redis:
    image: redis:7.0.0-alpine
    ports:
      - "6388:6379"
    command: redis-server

  mysql:
    image: mysql:8.0
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: coro_runner_tasks

  postgres:
    image: postgres:15
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: coro_runner_tasks
